### ISSUE TITLE
[docs] Obsolete example

### ISSUE THREAD

**Issue by pn11** [gpodder/podcastparser#36]
Docs on readthedocs.io looks obsolete compared to repo.

In example below, `urllib.urlopen` is used.
https://podcastparser.readthedocs.io/en/latest/#example

This does not work with current Python and  is already fixed in the commit below.
https://github.com/gpodder/podcastparser/pull/23

**Comment by thp** [comment]
cc @stefankoegl can you check if this needs changes? https://readthedocs.org/projects/podcastparser/

**Comment by auouymous** [comment]
That page also needs updating. It says `Last Built  3 years, 4 months ago passed` and links to the https://podcastparser.readthedocs.io/en/latest/ URL which says `0.6.4` in the title.

**Comment by stefankoegl** [comment]
I've now triggered a manual build and configured the webhook. As far as I can tell the project should now be built automatically.
