### ISSUE TITLE
Example with Requests

### ISSUE THREAD

**Issue by joelsgp** [gpodder/podcastparser#45]
What `stream` is meant to be isnt' that well documented so it took me a minute to figure out how to do that.

 I ended up with this:
```py
with requests.get(url, stream=True) as response:
    response.raw.decode_content = True
    parsed = podcastparser.parse(url, response.raw)
```
(from here https://stackoverflow.com/questions/21715298/python-requests-return-file-like-object-for-streaming)

I wasn't sure whether stream was meant to be binary or text, and whether it's meant to be the full response or just the contents

https://podcastparser.readthedocs.io/en/latest/#example

https://podcastparser.readthedocs.io/en/latest/#podcastparser.parse

thanks!

**Comment by thp** [comment]
Thanks, added to the docs now.
